apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: adop-gerrit
  annotations:
    description: "gerrit for ADOP"
    tags: "gerrit,adop"
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: gerrit-review-claim
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "1Gi"
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: gerrit-repos-claim
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "1Gi"
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${GERRIT_NAME}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${GERRIT_NAME}
      container: ${GERRIT_NAME}
      app: adop-${GERRIT_NAME}
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          deploymentconfig: ${GERRIT_NAME}
          container: ${GERRIT_NAME}
          app: adop-${GERRIT_NAME}
      spec:
        containers:
        - volumeMounts:
          - name: repos
            mountPath: /var/git/repos
          - name: review-site
            mountPath: /var/gerrit/review_site
          readinessProbe:
            httpGet:
              path: /gerrit
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
          - name: WEBURL
            value: "http://${GERRIT_NAME}-${PROJECT}.${SUB_DOMAIN}/gerrit/"
          - name: AUTH_LOGOUTURL
            value: "http://${GERRIT_NAME}-${PROJECT}.${SUB_DOMAIN}/gerrit/"
          - name: DATABASE_TYPE
            value: "mysql"
          - name: DB_HOSTNAME
            value: ${DB_HOSTNAME}
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: ${MYSQL_DATABASE}
          - name: DB_USER
            value: ${MYSQL_USER}
          - name: DB_PASSWORD
            value: ${MYSQL_PASSWORD}
          - name: AUTH_TYPE
            value: "LDAP"
          - name: GERRIT_PASSWORD
            value: ${GERRIT_PASSWORD}
          - name: JENKINS_PASSWORD
            value: ${JENKINS_PASSWORD}
          - name: INITIAL_ADMIN_USER
            value: ${INITIAL_ADMIN_USER}
          - name: INITIAL_ADMIN_PASSWORD
            value: ${INITIAL_ADMIN_PASSWORD}
          - name: LDAP_SERVER
            value: ${LDAP_SERVER}
          - name: LDAP_ACCOUNTBASE
            value: ${LDAP_ACCOUNTBASE}
          - name: LDAP_USERNAME
            value: ${LDAP_USERNAME}
          - name: LDAP_PASSWORD
            value: ${LDAP_PASSWORD}
          - name: HTTPD_LISTENURL
            value: proxy-http://0.0.0.0:8080/gerrit
          image: accenture/adop-gerrit:0.1.3
          imagePullPolicy: Always
          name: ${GERRIT_NAME}
          resources: {}
          terminationMessagePath: /dev/termination-log
        ports:
          - name: http
            containerPort: 8080
          - name: ssh
            containerPort: 29418
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        serviceAccount: adop
        volumes:
        - name: repos
          persistentVolumeClaim:
            claimName: gerrit-repos-claim
        - name: review-site
          persistentVolumeClaim:
            claimName: gerrit-review-claim
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${GERRIT_NAME}
    labels:
      service: ${GERRIT_NAME}
  spec:
    ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: ssh
      port: 29418
      targetPort: 29418
      protocol: TCP
    selector:
      deploymentconfig: ${GERRIT_NAME}
      container: ${GERRIT_NAME}
      app: adop-${GERRIT_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${GERRIT_NAME}
    labels:
      app: ${GERRIT_NAME}
  spec:
#    host: ${GERRIT_NAME}.${SUB_DOMAIN}
    to:
      kind: Service
      name: ${GERRIT_NAME}
    port:
      targetPort: http
  wildcardPolicy: None
parameters:
- description: "TODO"
  value: "gerrit"
  name: GERRIT_NAME
  required: true
- description: "TODO"
  value: "demo"
  name: PROJECT
  required: true
- description: "TODO"
  value: "cloudapps.example.com"
  name: SUB_DOMAIN
  required: true
- description: "TODO"
  value: "gerrit"
  name: MYSQL_DATABASE
  required: true
- description: "TODO"
  value: "gerrit"
  name: MYSQL_PASSWORD
  required: true
- description: "TODO"
  value: "gerrit"
  name: MYSQL_USER
  required: true
- description: "TODO"
  value: "gerrit-mysql"
  name: DB_HOSTNAME
  required: true
- description: "TODO"
  value: "gerrit"
  name: GERRIT_PASSWORD
  required: true
- description: "TODO"
  value: "jenkins"
  name: JENKINS_PASSWORD
  required: true
- description: "TODO"
  value: "adop"
  required: true
  name: INITIAL_ADMIN_USER
- description: "TODO"
  value: "adop"
  required: true
  name: INITIAL_ADMIN_PASSWORD
- description: "TODO"
  value: "ldap:389"
  required: true
  name: LDAP_SERVER
- description: "TODO"
  value: "dc=ldap,dc=example,dc=com"
  required: true
  name: LDAP_ACCOUNTBASE
- description: "TODO"
  value: "cn=admin,dc=ldap,dc=example,dc=com"
  required: true
  name: LDAP_USERNAME
- description: "TODO"
  value: "Jpk66g63ZifGYIcShSGM"
  required: true
  name: LDAP_PASSWORD
